names_total = {"ISU_SRT_CD": "종목코드",
               "ISU_CD": "표준종목코드",
               "ISU_ABBRV": "종목명",
               "MKT_NM": "시장구분",
               "SECT_TP_NM": "소속부",
               "TDD_CLSPRC": "종가",
               "FLUC_TP_CD": "?",
               "CMPPREVDD_PRC": "대비",
               "FLUC_RT": "등락률",
               "TDD_OPNPRC": "시가",
               "TDD_HGPRC": "고가",
               "TDD_LWPRC": "저가",
               "ACC_TRDVOL": "거래량",
               "ACC_TRDVAL": "거래대금",
               "MKTCAP": "시가총액",
               "LIST_SHRS": "상장주식수",
               "MKT_ID": "시장코드",
               "BAS_PRC": "시작일 기준가",
               "FLUC_TP": "?",
               'full_code': '표준종목코드',
               'short_code': '종목코드',
               'codeName': '종목명',
               'marketCode': '시장코드',
               'marketName': 'marketName',
               'marketEngName': '시장구분',
               'ord1': 'ord1',
               'ord2': 'ord2',
               "TRD_DD": "일자"
               }
